### ISSUE TITLE
Docker/Podman - Error after deployment - SqliteError: unable to open database file

### ISSUE THREAD

**Issue by RiQuY** [nodecg/nodecg#739]
Deploying NodeCG 2.2.2 with Docker or Podman I get the following error on the every container startup:

```yaml
2024-07-09 21:16:21 - info: [server] Starting NodeCG 2.2.2 (Running on Node.js v18.20.3)
SqliteError: unable to open database file
    at new Database (/opt/nodecg/node_modules/better-sqlite3/lib/database.js:69:26)
    at BetterSqlite3Driver.Database [as sqlite] (/opt/nodecg/node_modules/better-sqlite3/lib/database.js:11:10)
    at BetterSqlite3Driver.createDatabaseConnection (/opt/nodecg/node_modules/typeorm/driver/better-sqlite3/BetterSqlite3Driver.js:88:41)
    at async BetterSqlite3Driver.connect (/opt/nodecg/node_modules/typeorm/driver/sqlite-abstract/AbstractSqliteDriver.js:171:35)
    at async DataSource.initialize (/opt/nodecg/node_modules/typeorm/data-source/DataSource.js:136:9) {
  code: 'SQLITE_CANTOPEN'
}
```

I tried the deployment in 2 different machines to rule out a permission error, same error in both machines.
- Machine 1: OpenMediaVault 7 (Debian 12) with docker-ce 5:27.0.3-1 and docker-compose-plugin 2.28.1-1
- Machine 2: openSUSE Tumbleweed with podman 5.1.1-2.1

I also tried deploying with different tags: latest, 2.2, 2.2.0, 2.1, 2.0. The guide I followed was this one from the official docs https://www.nodecg.dev/docs/docker

I tried 2 different docker-compose files with the same result, the folder mounts are created but with no files inside and I verified that I don't need to run the docker commands with `sudo` because I have other containers running successfully:

**Docker attempt in Debian 12**

`docker-compose up -d`
```yaml
services:
  nodecg:
    image: 'ghcr.io/nodecg/nodecg'
    container_name: 'nodecg'
    ports:
      - '9090:9090'
    volumes:
      - './cfg:/opt/nodecg/cfg'
      - './bundles:/opt/nodecg/bundles'
      - './logs:/opt/nodecg/logs'
      - './db:/opt/nodecg/db'
      - './assets:/opt/nodecg/assets'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
```

The enviroment variables in the previous code come from this file `global.env`:
```ini
PUID=1001
PGID=100
TZ=Europe/Madrid
```

**Podman attempt in openSUSE Tumbleweed**

`podman-compose up -d`
```yaml
services:
  nodecg:
    image: 'ghcr.io/nodecg/nodecg'
    container_name: 'nodecg'
    ports:
      - '9090:9090'
    volumes:
      - /media/Almacen/Archivos/podman/nodecg/cfg:/opt/nodecg/cfg
      - /media/Almacen/Archivos/podman/nodecg/bundles:/opt/nodecg/bundles
      - /media/Almacen/Archivos/podman/nodecg/logs:/opt/nodecg/logs
      - /media/Almacen/Archivos/podman/nodecg/db:/opt/nodecg/db
      - /media/Almacen/Archivos/podman/nodecg/assets:/opt/nodecg/assets
```
