### ISSUE TITLE
per-workspace CI config

### ISSUE THREAD

**Issue by Hoishin** [nodecg/nodecg#828]
Use
```yaml
on:
  push:
    paths:
      - workspaces/<workspace name>
```
to conditionally run test
